
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

# Uncomment to update deps with dep tool
# ignored = ["sigs.k8s.io/apiserver-builder-alpha","sigs.k8s.io/apiserver-builder-alpha/cmd"]

required = [
  "github.com/json-iterator/go",
  "github.com/coreos/etcd",
  "google.golang.org/genproto",
  "google.golang.org/grpc",
  "github.com/imdario/mergo",
  "k8s.io/kube-openapi/cmd/openapi-gen",
  "github.com/modern-go/reflect2",
  "sigs.k8s.io/controller-runtime/pkg/envtest",
  "sigs.k8s.io/controller-runtime/pkg/client",
  "sigs.k8s.io/controller-runtime/pkg/client/fake",
  "sigs.k8s.io/controller-runtime/pkg/controller",
  "sigs.k8s.io/controller-runtime/pkg/runtime/signals",
]

# Comment to update deps with dep tool
#[[constraint]]
#  version = "v1.15.alpha.0"
#  name = "sigs.k8s.io/apiserver-builder-alpha"

[[constraint]]
  name = "github.com/emicklei/go-restful"

[[constraint]]
  name = "github.com/go-openapi/loads"

[[constraint]]
  name = "github.com/go-openapi/runtime"

[[constraint]]
  name = "github.com/go-openapi/spec"

[[constraint]]
  name = "github.com/go-openapi/validate"

[[constraint]]
  branch = "master"
  name = "github.com/markbates/inflect"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/pflag"

[[constraint]]
  name = "github.com/spf13/viper"

[[override]]
  version = "kubernetes-1.15.3"
  name = "k8s.io/api"

[[override]]
  version = "kubernetes-1.15.3"
  name = "k8s.io/apiextensions-apiserver"

[[override]]
  version = "kubernetes-1.15.3"
  name = "k8s.io/kube-aggregator"

[[override]]
  version = "kubernetes-1.15.3"
  name = "k8s.io/apimachinery"

[[override]]
  version = "kubernetes-1.15.3"
  name = "k8s.io/apiserver"

[[override]]
  version = "v12.0.0"
  name = "k8s.io/client-go"

[[constraint]]
  name = "k8s.io/gengo"
  revision = "fdcf9f9480fdd5bf2b3c3df9bf4ecd22b25b87e2"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "b3a7cee44a305be0a69e1b9ac03018307287e1b0"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "=0.3.5"

[[constraint]]
  name = "github.com/modern-go/reflect2"
  version = "1.0.1"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "v11.1.2"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"
  version="v1.4.7"

[prune]
  unused-packages = true
  non-go = true
  [[prune.project]]
    name = "k8s.io/apimachinery"
    unused-packages = false
    non-go = false
  [[prune.project]]
    name = "github.com/gogo/protobuf"
    unused-packages = false
    non-go = false

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.2.0-rc.0"

[[override]]
  name = "sigs.k8s.io/structured-merge-diff"
  revision = "e85c7b244fd2cc57bb829d73a061f93a441e63ce"

[[constraint]]
  name = "github.com/rancher/kine"
  revision = "c308515dee837fd00d480e482f763d76e7572df5"
  source = "https://github.com/ibuildthecloud/kine"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "v3.3.13"
