/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/WanLinghao/coredump-detector/pkg/apis/coredump/v1alpha1"
	scheme "github.com/WanLinghao/coredump-detector/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CoredumpEndpointsGetter has a method to return a CoredumpEndpointInterface.
// A group's client should implement this interface.
type CoredumpEndpointsGetter interface {
	CoredumpEndpoints(namespace string) CoredumpEndpointInterface
}

// CoredumpEndpointInterface has methods to work with CoredumpEndpoint resources.
type CoredumpEndpointInterface interface {
	Create(*v1alpha1.CoredumpEndpoint) (*v1alpha1.CoredumpEndpoint, error)
	Update(*v1alpha1.CoredumpEndpoint) (*v1alpha1.CoredumpEndpoint, error)
	UpdateStatus(*v1alpha1.CoredumpEndpoint) (*v1alpha1.CoredumpEndpoint, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CoredumpEndpoint, error)
	List(opts v1.ListOptions) (*v1alpha1.CoredumpEndpointList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CoredumpEndpoint, err error)
	CoredumpEndpointExpansion
}

// coredumpEndpoints implements CoredumpEndpointInterface
type coredumpEndpoints struct {
	client rest.Interface
	ns     string
}

// newCoredumpEndpoints returns a CoredumpEndpoints
func newCoredumpEndpoints(c *CoredumpV1alpha1Client, namespace string) *coredumpEndpoints {
	return &coredumpEndpoints{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the coredumpEndpoint, and returns the corresponding coredumpEndpoint object, and an error if there is any.
func (c *coredumpEndpoints) Get(name string, options v1.GetOptions) (result *v1alpha1.CoredumpEndpoint, err error) {
	result = &v1alpha1.CoredumpEndpoint{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("coredumpendpoints").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CoredumpEndpoints that match those selectors.
func (c *coredumpEndpoints) List(opts v1.ListOptions) (result *v1alpha1.CoredumpEndpointList, err error) {
	result = &v1alpha1.CoredumpEndpointList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("coredumpendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested coredumpEndpoints.
func (c *coredumpEndpoints) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("coredumpendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a coredumpEndpoint and creates it.  Returns the server's representation of the coredumpEndpoint, and an error, if there is any.
func (c *coredumpEndpoints) Create(coredumpEndpoint *v1alpha1.CoredumpEndpoint) (result *v1alpha1.CoredumpEndpoint, err error) {
	result = &v1alpha1.CoredumpEndpoint{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("coredumpendpoints").
		Body(coredumpEndpoint).
		Do().
		Into(result)
	return
}

// Update takes the representation of a coredumpEndpoint and updates it. Returns the server's representation of the coredumpEndpoint, and an error, if there is any.
func (c *coredumpEndpoints) Update(coredumpEndpoint *v1alpha1.CoredumpEndpoint) (result *v1alpha1.CoredumpEndpoint, err error) {
	result = &v1alpha1.CoredumpEndpoint{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("coredumpendpoints").
		Name(coredumpEndpoint.Name).
		Body(coredumpEndpoint).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *coredumpEndpoints) UpdateStatus(coredumpEndpoint *v1alpha1.CoredumpEndpoint) (result *v1alpha1.CoredumpEndpoint, err error) {
	result = &v1alpha1.CoredumpEndpoint{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("coredumpendpoints").
		Name(coredumpEndpoint.Name).
		SubResource("status").
		Body(coredumpEndpoint).
		Do().
		Into(result)
	return
}

// Delete takes name of the coredumpEndpoint and deletes it. Returns an error if one occurs.
func (c *coredumpEndpoints) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("coredumpendpoints").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *coredumpEndpoints) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("coredumpendpoints").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched coredumpEndpoint.
func (c *coredumpEndpoints) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CoredumpEndpoint, err error) {
	result = &v1alpha1.CoredumpEndpoint{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("coredumpendpoints").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
