/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/WanLinghao/coredump-detector/pkg/apis/coredump/v1alpha1"
	scheme "github.com/WanLinghao/coredump-detector/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CoredumpEndpointDumpsGetter has a method to return a CoredumpEndpointDumpInterface.
// A group's client should implement this interface.
type CoredumpEndpointDumpsGetter interface {
	CoredumpEndpointDumps(namespace string) CoredumpEndpointDumpInterface
}

// CoredumpEndpointDumpInterface has methods to work with CoredumpEndpointDump resources.
type CoredumpEndpointDumpInterface interface {
	Create(*v1alpha1.CoredumpEndpointDump) (*v1alpha1.CoredumpEndpointDump, error)
	Update(*v1alpha1.CoredumpEndpointDump) (*v1alpha1.CoredumpEndpointDump, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CoredumpEndpointDump, error)
	List(opts v1.ListOptions) (*v1alpha1.CoredumpEndpointDumpList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CoredumpEndpointDump, err error)
	CoredumpEndpointDumpExpansion
}

// coredumpEndpointDumps implements CoredumpEndpointDumpInterface
type coredumpEndpointDumps struct {
	client rest.Interface
	ns     string
}

// newCoredumpEndpointDumps returns a CoredumpEndpointDumps
func newCoredumpEndpointDumps(c *CoredumpV1alpha1Client, namespace string) *coredumpEndpointDumps {
	return &coredumpEndpointDumps{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the coredumpEndpointDump, and returns the corresponding coredumpEndpointDump object, and an error if there is any.
func (c *coredumpEndpointDumps) Get(name string, options v1.GetOptions) (result *v1alpha1.CoredumpEndpointDump, err error) {
	result = &v1alpha1.CoredumpEndpointDump{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("coredumpendpointdumps").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CoredumpEndpointDumps that match those selectors.
func (c *coredumpEndpointDumps) List(opts v1.ListOptions) (result *v1alpha1.CoredumpEndpointDumpList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CoredumpEndpointDumpList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("coredumpendpointdumps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested coredumpEndpointDumps.
func (c *coredumpEndpointDumps) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("coredumpendpointdumps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a coredumpEndpointDump and creates it.  Returns the server's representation of the coredumpEndpointDump, and an error, if there is any.
func (c *coredumpEndpointDumps) Create(coredumpEndpointDump *v1alpha1.CoredumpEndpointDump) (result *v1alpha1.CoredumpEndpointDump, err error) {
	result = &v1alpha1.CoredumpEndpointDump{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("coredumpendpointdumps").
		Body(coredumpEndpointDump).
		Do().
		Into(result)
	return
}

// Update takes the representation of a coredumpEndpointDump and updates it. Returns the server's representation of the coredumpEndpointDump, and an error, if there is any.
func (c *coredumpEndpointDumps) Update(coredumpEndpointDump *v1alpha1.CoredumpEndpointDump) (result *v1alpha1.CoredumpEndpointDump, err error) {
	result = &v1alpha1.CoredumpEndpointDump{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("coredumpendpointdumps").
		Name(coredumpEndpointDump.Name).
		Body(coredumpEndpointDump).
		Do().
		Into(result)
	return
}

// Delete takes name of the coredumpEndpointDump and deletes it. Returns an error if one occurs.
func (c *coredumpEndpointDumps) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("coredumpendpointdumps").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *coredumpEndpointDumps) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("coredumpendpointdumps").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched coredumpEndpointDump.
func (c *coredumpEndpointDumps) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CoredumpEndpointDump, err error) {
	result = &v1alpha1.CoredumpEndpointDump{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("coredumpendpointdumps").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
