// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apis/coredump/v1alpha1/coredump.proto

package v1alpha1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import v1 "vendor/k8s.io/apimachinery/pkg/apis/meta/v1"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CoredumpEndpointList struct {
	// Standard list metadata.
	// More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
	// +optional
	Metadata *v1.ListMeta `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	// List of pods.
	// More info: https://git.k8s.io/community/contributors/devel/api-conventions.md
	Items                []*CoredumpEndpoint `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CoredumpEndpointList) Reset()         { *m = CoredumpEndpointList{} }
func (m *CoredumpEndpointList) String() string { return proto.CompactTextString(m) }
func (*CoredumpEndpointList) ProtoMessage()    {}
func (*CoredumpEndpointList) Descriptor() ([]byte, []int) {
	return fileDescriptor_coredump_13c9bbfe6c8d4231, []int{0}
}
func (m *CoredumpEndpointList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoredumpEndpointList.Unmarshal(m, b)
}
func (m *CoredumpEndpointList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoredumpEndpointList.Marshal(b, m, deterministic)
}
func (dst *CoredumpEndpointList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoredumpEndpointList.Merge(dst, src)
}
func (m *CoredumpEndpointList) XXX_Size() int {
	return xxx_messageInfo_CoredumpEndpointList.Size(m)
}
func (m *CoredumpEndpointList) XXX_DiscardUnknown() {
	xxx_messageInfo_CoredumpEndpointList.DiscardUnknown(m)
}

var xxx_messageInfo_CoredumpEndpointList proto.InternalMessageInfo

func (m *CoredumpEndpointList) GetMetadata() *v1.ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CoredumpEndpointList) GetItems() []*CoredumpEndpoint {
	if m != nil {
		return m.Items
	}
	return nil
}

type CoredumpEndpoint struct {
	// Standard object's metadata.
	// More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
	// +optional
	Metadata *v1.ObjectMeta `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	// Specification of the desired behavior of the pod.
	// More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status
	// +optional
	Spec *CoredumpEndpointSpec `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	// Most recently observed status of the pod.
	// This data may not be up to date.
	// Populated by the system.
	// Read-only.
	// More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status
	// +optional
	Status               *CoredumpEndpointStatus `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CoredumpEndpoint) Reset()         { *m = CoredumpEndpoint{} }
func (m *CoredumpEndpoint) String() string { return proto.CompactTextString(m) }
func (*CoredumpEndpoint) ProtoMessage()    {}
func (*CoredumpEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_coredump_13c9bbfe6c8d4231, []int{1}
}
func (m *CoredumpEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoredumpEndpoint.Unmarshal(m, b)
}
func (m *CoredumpEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoredumpEndpoint.Marshal(b, m, deterministic)
}
func (dst *CoredumpEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoredumpEndpoint.Merge(dst, src)
}
func (m *CoredumpEndpoint) XXX_Size() int {
	return xxx_messageInfo_CoredumpEndpoint.Size(m)
}
func (m *CoredumpEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_CoredumpEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_CoredumpEndpoint proto.InternalMessageInfo

func (m *CoredumpEndpoint) GetMetadata() *v1.ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CoredumpEndpoint) GetSpec() *CoredumpEndpointSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *CoredumpEndpoint) GetStatus() *CoredumpEndpointStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type CoredumpEndpointSpec struct {
	PodUID               *string  `protobuf:"bytes,1,opt,name=podUID" json:"podUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoredumpEndpointSpec) Reset()         { *m = CoredumpEndpointSpec{} }
func (m *CoredumpEndpointSpec) String() string { return proto.CompactTextString(m) }
func (*CoredumpEndpointSpec) ProtoMessage()    {}
func (*CoredumpEndpointSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_coredump_13c9bbfe6c8d4231, []int{2}
}
func (m *CoredumpEndpointSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoredumpEndpointSpec.Unmarshal(m, b)
}
func (m *CoredumpEndpointSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoredumpEndpointSpec.Marshal(b, m, deterministic)
}
func (dst *CoredumpEndpointSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoredumpEndpointSpec.Merge(dst, src)
}
func (m *CoredumpEndpointSpec) XXX_Size() int {
	return xxx_messageInfo_CoredumpEndpointSpec.Size(m)
}
func (m *CoredumpEndpointSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_CoredumpEndpointSpec.DiscardUnknown(m)
}

var xxx_messageInfo_CoredumpEndpointSpec proto.InternalMessageInfo

func (m *CoredumpEndpointSpec) GetPodUID() string {
	if m != nil && m.PodUID != nil {
		return *m.PodUID
	}
	return ""
}

type CoredumpEndpointStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoredumpEndpointStatus) Reset()         { *m = CoredumpEndpointStatus{} }
func (m *CoredumpEndpointStatus) String() string { return proto.CompactTextString(m) }
func (*CoredumpEndpointStatus) ProtoMessage()    {}
func (*CoredumpEndpointStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_coredump_13c9bbfe6c8d4231, []int{3}
}
func (m *CoredumpEndpointStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoredumpEndpointStatus.Unmarshal(m, b)
}
func (m *CoredumpEndpointStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoredumpEndpointStatus.Marshal(b, m, deterministic)
}
func (dst *CoredumpEndpointStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoredumpEndpointStatus.Merge(dst, src)
}
func (m *CoredumpEndpointStatus) XXX_Size() int {
	return xxx_messageInfo_CoredumpEndpointStatus.Size(m)
}
func (m *CoredumpEndpointStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_CoredumpEndpointStatus.DiscardUnknown(m)
}

var xxx_messageInfo_CoredumpEndpointStatus proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CoredumpEndpointList)(nil), "v1alpha1.CoredumpEndpointList")
	proto.RegisterType((*CoredumpEndpoint)(nil), "v1alpha1.CoredumpEndpoint")
	proto.RegisterType((*CoredumpEndpointSpec)(nil), "v1alpha1.CoredumpEndpointSpec")
	proto.RegisterType((*CoredumpEndpointStatus)(nil), "v1alpha1.CoredumpEndpointStatus")
}

func init() {
	proto.RegisterFile("pkg/apis/coredump/v1alpha1/coredump.proto", fileDescriptor_coredump_13c9bbfe6c8d4231)
}

var fileDescriptor_coredump_13c9bbfe6c8d4231 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0xab, 0xa5, 0x6e, 0x2f, 0xb2, 0x48, 0x09, 0x3d, 0x48, 0xc8, 0xa9, 0x5e, 0x66,
	0x9b, 0x9c, 0x0a, 0x1e, 0xd5, 0x83, 0x52, 0x11, 0x22, 0x3e, 0xc0, 0x9a, 0x1d, 0xd2, 0x35, 0x26,
	0xbb, 0x64, 0xb7, 0x01, 0xdf, 0xc3, 0xe7, 0xf2, 0x99, 0x64, 0x93, 0x34, 0x48, 0xaa, 0xd2, 0x63,
	0x66, 0xfe, 0xef, 0x9b, 0x3f, 0x4b, 0xae, 0x74, 0x9e, 0x31, 0xae, 0xa5, 0x61, 0xa9, 0xaa, 0x50,
	0xec, 0x0a, 0xcd, 0xea, 0x88, 0xbf, 0xeb, 0x2d, 0x8f, 0xfa, 0x09, 0xe8, 0x4a, 0x59, 0x45, 0xa7,
	0xfb, 0xc5, 0xe2, 0xba, 0xc6, 0x52, 0xa8, 0x8a, 0xe5, 0x6b, 0x03, 0x52, 0x39, 0xbc, 0xe0, 0xe9,
	0x56, 0x96, 0x58, 0x7d, 0xb0, 0xde, 0x57, 0xa0, 0xe5, 0xac, 0x8e, 0x58, 0x86, 0x25, 0x56, 0xdc,
	0xa2, 0x68, 0x35, 0xe1, 0xa7, 0x47, 0x2e, 0x6e, 0x3a, 0xf3, 0x5d, 0x29, 0xb4, 0x92, 0xa5, 0xdd,
	0x48, 0x63, 0xe9, 0x03, 0x99, 0x3a, 0x46, 0x70, 0xcb, 0x7d, 0x2f, 0xf0, 0x96, 0xb3, 0x18, 0xa0,
	0xbd, 0x00, 0x3f, 0x2f, 0x80, 0xce, 0x33, 0x37, 0x30, 0xe0, 0xd2, 0x50, 0x47, 0xe0, 0xe8, 0x47,
	0xb4, 0x3c, 0xe9, 0x79, 0xba, 0x22, 0xa7, 0xd2, 0x62, 0x61, 0xfc, 0x51, 0x30, 0x5e, 0xce, 0xe2,
	0x05, 0xec, 0xbb, 0xc3, 0xf0, 0x74, 0xd2, 0x06, 0xc3, 0x2f, 0x8f, 0x9c, 0x0f, 0x77, 0x74, 0x73,
	0x50, 0x69, 0x75, 0x5c, 0xa5, 0xa7, 0xd7, 0x37, 0x4c, 0x87, 0xa5, 0x62, 0x72, 0x62, 0x34, 0xa6,
	0xfe, 0xa8, 0x31, 0x5d, 0xfe, 0xdd, 0xe9, 0x59, 0x63, 0x9a, 0x34, 0x59, 0xba, 0x26, 0x13, 0x63,
	0xb9, 0xdd, 0x19, 0x7f, 0xdc, 0x50, 0xc1, 0x3f, 0x54, 0x93, 0x4b, 0xba, 0x7c, 0x08, 0x87, 0xcf,
	0xec, 0xbc, 0x74, 0x4e, 0x26, 0x5a, 0x89, 0x97, 0xfb, 0xdb, 0xe6, 0x8f, 0xce, 0x92, 0xee, 0x2b,
	0xf4, 0xc9, 0xfc, 0x77, 0xe3, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x86, 0xac, 0xbe, 0x83, 0x24,
	0x02, 0x00, 0x00,
}
